site_name: Smallrye Mutiny Zero
repo_url: https://github.com/smallrye/smallrye-mutiny-zero
edit_uri: edit/main/docs/

nav:
  - Overview: 'index.md'
  - 'quick-start.md'
  - Javadoc: './apidocs/index.html'
  - 'flow-adapters.md'
  - 'vertx-based-reactive-streams-publishers.md'

theme:
  name: material
  palette:
    primary: white
    accent: red
  features:
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: '#'
  - admonition
  - smarty
  - attr_list
  - md_in_html
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  manifest: manifest.webmanifest
  version:
    provider: mike
