---
name: Main CI/CD pipeline
on:
  push:
    branches:
      - main

jobs:

  build-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '11', 'opts': '' },
          { 'version': '17', 'opts': '' }
        ]
    name: Build with Java ${{ matrix.java.version }} (OpenJDK)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Set up JDK ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven
      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: ./mvnw -s .github/maven-ci-settings.xml -B clean verify

  deploy:
    name: Deployment
    needs: build-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
        run: |
          .github/scripts/decrypt-secrets.sh
          .github/scripts/deploy.sh

  compatibility:
    runs-on: ubuntu-latest
    name: Compatibility Check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Compatibility Check
        run: ./mvnw -s .github/maven-ci-settings.xml -B install revapi:check@check-compatibility -DskipTests -fae
