name: Publish the website
on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          fetch-depth: 0 # fetch all commits and branches for mike to work properly
      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: 3.x
      - name: Tools setup
        run: |
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"
          sudo snap install yq
          pip install mkdocs-material
          pip install mike          
      - name: Build local artifacts
        run: ./mvnw -B install -DskipTests
      - name: Render docs and publish
        run: .github/scripts/render-documentation.sh